/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MockOffchainAggregator } from "./MockOffchainAggregator";
export type { MockV3Aggregator } from "./MockV3Aggregator";
