/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../../../../common";

export interface IPoolInterface extends utils.Interface {
  functions: {
    "getToken()": FunctionFragment;
    "lockOrBurn(address,bytes,uint256,uint64,bytes)": FunctionFragment;
    "releaseOrMint(bytes,address,uint256,uint64,bytes)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getToken" | "lockOrBurn" | "releaseOrMint"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockOrBurn",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "releaseOrMint",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string;

  decodeFunctionResult(functionFragment: "getToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lockOrBurn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "releaseOrMint",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IPool extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IPoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getToken(overrides?: CallOverrides): Promise<[string] & { token: string }>;

    lockOrBurn(
      originalSender: PromiseOrValue<string>,
      receiver: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraArgs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    releaseOrMint(
      originalSender: PromiseOrValue<BytesLike>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getToken(overrides?: CallOverrides): Promise<string>;

  lockOrBurn(
    originalSender: PromiseOrValue<string>,
    receiver: PromiseOrValue<BytesLike>,
    amount: PromiseOrValue<BigNumberish>,
    remoteChainSelector: PromiseOrValue<BigNumberish>,
    extraArgs: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  releaseOrMint(
    originalSender: PromiseOrValue<BytesLike>,
    receiver: PromiseOrValue<string>,
    amount: PromiseOrValue<BigNumberish>,
    remoteChainSelector: PromiseOrValue<BigNumberish>,
    extraData: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getToken(overrides?: CallOverrides): Promise<string>;

    lockOrBurn(
      originalSender: PromiseOrValue<string>,
      receiver: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraArgs: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<string>;

    releaseOrMint(
      originalSender: PromiseOrValue<BytesLike>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getToken(overrides?: CallOverrides): Promise<BigNumber>;

    lockOrBurn(
      originalSender: PromiseOrValue<string>,
      receiver: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraArgs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    releaseOrMint(
      originalSender: PromiseOrValue<BytesLike>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    lockOrBurn(
      originalSender: PromiseOrValue<string>,
      receiver: PromiseOrValue<BytesLike>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraArgs: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    releaseOrMint(
      originalSender: PromiseOrValue<BytesLike>,
      receiver: PromiseOrValue<string>,
      amount: PromiseOrValue<BigNumberish>,
      remoteChainSelector: PromiseOrValue<BigNumberish>,
      extraData: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
