/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace MockEvm2EvmOffRamp {
  export type DynamicConfigStruct = {
    permissionLessExecutionThresholdSeconds: PromiseOrValue<BigNumberish>;
    router: PromiseOrValue<string>;
    priceRegistry: PromiseOrValue<string>;
    maxNumberOfTokensPerMsg: PromiseOrValue<BigNumberish>;
    maxDataBytes: PromiseOrValue<BigNumberish>;
    maxPoolReleaseOrMintGas: PromiseOrValue<BigNumberish>;
  };

  export type DynamicConfigStructOutput = [
    number,
    string,
    string,
    number,
    number,
    number
  ] & {
    permissionLessExecutionThresholdSeconds: number;
    router: string;
    priceRegistry: string;
    maxNumberOfTokensPerMsg: number;
    maxDataBytes: number;
    maxPoolReleaseOrMintGas: number;
  };
}

export declare namespace RateLimiter {
  export type ConfigStruct = {
    isEnabled: PromiseOrValue<boolean>;
    capacity: PromiseOrValue<BigNumberish>;
    rate: PromiseOrValue<BigNumberish>;
  };

  export type ConfigStructOutput = [boolean, BigNumber, BigNumber] & {
    isEnabled: boolean;
    capacity: BigNumber;
    rate: BigNumber;
  };

  export type TokenBucketStruct = {
    tokens: PromiseOrValue<BigNumberish>;
    lastUpdated: PromiseOrValue<BigNumberish>;
    isEnabled: PromiseOrValue<boolean>;
    capacity: PromiseOrValue<BigNumberish>;
    rate: PromiseOrValue<BigNumberish>;
  };

  export type TokenBucketStructOutput = [
    BigNumber,
    number,
    boolean,
    BigNumber,
    BigNumber
  ] & {
    tokens: BigNumber;
    lastUpdated: number;
    isEnabled: boolean;
    capacity: BigNumber;
    rate: BigNumber;
  };
}

export declare namespace Client {
  export type EVMTokenAmountStruct = {
    token: PromiseOrValue<string>;
    amount: PromiseOrValue<BigNumberish>;
  };

  export type EVMTokenAmountStructOutput = [string, BigNumber] & {
    token: string;
    amount: BigNumber;
  };
}

export declare namespace Internal {
  export type EVM2EVMMessageStruct = {
    sourceChainSelector: PromiseOrValue<BigNumberish>;
    sender: PromiseOrValue<string>;
    receiver: PromiseOrValue<string>;
    sequenceNumber: PromiseOrValue<BigNumberish>;
    gasLimit: PromiseOrValue<BigNumberish>;
    strict: PromiseOrValue<boolean>;
    nonce: PromiseOrValue<BigNumberish>;
    feeToken: PromiseOrValue<string>;
    feeTokenAmount: PromiseOrValue<BigNumberish>;
    data: PromiseOrValue<BytesLike>;
    tokenAmounts: Client.EVMTokenAmountStruct[];
    sourceTokenData: PromiseOrValue<BytesLike>[];
    messageId: PromiseOrValue<BytesLike>;
  };

  export type EVM2EVMMessageStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    boolean,
    BigNumber,
    string,
    BigNumber,
    string,
    Client.EVMTokenAmountStructOutput[],
    string[],
    string
  ] & {
    sourceChainSelector: BigNumber;
    sender: string;
    receiver: string;
    sequenceNumber: BigNumber;
    gasLimit: BigNumber;
    strict: boolean;
    nonce: BigNumber;
    feeToken: string;
    feeTokenAmount: BigNumber;
    data: string;
    tokenAmounts: Client.EVMTokenAmountStructOutput[];
    sourceTokenData: string[];
    messageId: string;
  };
}

export interface MockEvm2EvmOffRampInterface extends utils.Interface {
  functions: {
    "acceptOwnership()": FunctionFragment;
    "currentRateLimiterState()": FunctionFragment;
    "executeSingleMessage((uint64,address,address,uint64,uint256,bool,uint64,address,uint256,bytes,(address,uint256)[],bytes[],bytes32),bytes[])": FunctionFragment;
    "getPoolBySourceToken(address)": FunctionFragment;
    "getTokenLimitAdmin()": FunctionFragment;
    "owner()": FunctionFragment;
    "setAdmin(address)": FunctionFragment;
    "setRateLimiterConfig((bool,uint128,uint128))": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "acceptOwnership"
      | "currentRateLimiterState"
      | "executeSingleMessage"
      | "getPoolBySourceToken"
      | "getTokenLimitAdmin"
      | "owner"
      | "setAdmin"
      | "setRateLimiterConfig"
      | "transferOwnership"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentRateLimiterState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "executeSingleMessage",
    values: [Internal.EVM2EVMMessageStruct, PromiseOrValue<BytesLike>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolBySourceToken",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenLimitAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAdmin",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setRateLimiterConfig",
    values: [RateLimiter.ConfigStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentRateLimiterState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeSingleMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPoolBySourceToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTokenLimitAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setRateLimiterConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "AdminSet(address)": EventFragment;
    "OwnershipTransferRequested(address,address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "AdminSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferRequested"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export interface AdminSetEventObject {
  newAdmin: string;
}
export type AdminSetEvent = TypedEvent<[string], AdminSetEventObject>;

export type AdminSetEventFilter = TypedEventFilter<AdminSetEvent>;

export interface OwnershipTransferRequestedEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferRequestedEvent = TypedEvent<
  [string, string],
  OwnershipTransferRequestedEventObject
>;

export type OwnershipTransferRequestedEventFilter =
  TypedEventFilter<OwnershipTransferRequestedEvent>;

export interface OwnershipTransferredEventObject {
  from: string;
  to: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface MockEvm2EvmOffRamp extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MockEvm2EvmOffRampInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    currentRateLimiterState(
      overrides?: CallOverrides
    ): Promise<[RateLimiter.TokenBucketStructOutput]>;

    executeSingleMessage(
      message: Internal.EVM2EVMMessageStruct,
      offchainTokenData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getPoolBySourceToken(
      sourceToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[string]>;

    getTokenLimitAdmin(overrides?: CallOverrides): Promise<[string]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    setAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setRateLimiterConfig(
      config: RateLimiter.ConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  acceptOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  currentRateLimiterState(
    overrides?: CallOverrides
  ): Promise<RateLimiter.TokenBucketStructOutput>;

  executeSingleMessage(
    message: Internal.EVM2EVMMessageStruct,
    offchainTokenData: PromiseOrValue<BytesLike>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getPoolBySourceToken(
    sourceToken: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<string>;

  getTokenLimitAdmin(overrides?: CallOverrides): Promise<string>;

  owner(overrides?: CallOverrides): Promise<string>;

  setAdmin(
    newAdmin: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setRateLimiterConfig(
    config: RateLimiter.ConfigStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptOwnership(overrides?: CallOverrides): Promise<void>;

    currentRateLimiterState(
      overrides?: CallOverrides
    ): Promise<RateLimiter.TokenBucketStructOutput>;

    executeSingleMessage(
      message: Internal.EVM2EVMMessageStruct,
      offchainTokenData: PromiseOrValue<BytesLike>[],
      overrides?: CallOverrides
    ): Promise<void>;

    getPoolBySourceToken(
      sourceToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<string>;

    getTokenLimitAdmin(overrides?: CallOverrides): Promise<string>;

    owner(overrides?: CallOverrides): Promise<string>;

    setAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setRateLimiterConfig(
      config: RateLimiter.ConfigStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "AdminSet(address)"(newAdmin?: null): AdminSetEventFilter;
    AdminSet(newAdmin?: null): AdminSetEventFilter;

    "OwnershipTransferRequested(address,address)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferRequestedEventFilter;
    OwnershipTransferRequested(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferRequestedEventFilter;

    "OwnershipTransferred(address,address)"(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
  };

  estimateGas: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    currentRateLimiterState(overrides?: CallOverrides): Promise<BigNumber>;

    executeSingleMessage(
      message: Internal.EVM2EVMMessageStruct,
      offchainTokenData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getPoolBySourceToken(
      sourceToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getTokenLimitAdmin(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    setAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setRateLimiterConfig(
      config: RateLimiter.ConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    currentRateLimiterState(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    executeSingleMessage(
      message: Internal.EVM2EVMMessageStruct,
      offchainTokenData: PromiseOrValue<BytesLike>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getPoolBySourceToken(
      sourceToken: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTokenLimitAdmin(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAdmin(
      newAdmin: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setRateLimiterConfig(
      config: RateLimiter.ConfigStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
